name: Mirror

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  Deploy:
    timeout-minutes: 25
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Make envfile  
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_STREAMABLE_EMAIL: ${{ secrets.STREAMABLE_USERNAME }}
          envkey_STREAMABLE_PASSWORD: ${{ secrets.STREAMABLE_PASSWORD }}
          envkey_REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          envkey_REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          envkey_REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          envkey_REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          envkey_MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}
          envkey_MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
          file_name: .env
          
      - name: Run bot
        run: docker-compose up --build app
